In [18]:
import pandas as pd
import re

In [19]:
df = pd.read_csv("../data/raw/100canciones_rock_argentino.csv")
print(f"{len(df)} rows")
df.head(3)

100 rows

,Posición,Título,Artista,Año,lyrics
0,1,La balsa,Los Gatos,1967,"6 ContributorsLa Balsa Lyrics[Letra de ""La Bal..."
1,2,Muchacha (Ojos de papel),Almendra,1970,16 ContributorsTranslationsEnglishMuchacha (Oj...
2,3,Rasguña las piedras,Sui Generis,1973,10 ContributorsRasguña las Piedras Lyrics[Letr...

In [20]:
# Modify column names: lower case, replace spaces and hyphens with underscores, and remove non-alphanumeric characters
df.columns = (
    df.columns.str.lower()  # Convert to lowercase
    .str.replace(" ", "_")  # Replace spaces with underscores
    .str.replace("-", "_")  # Replace hyphens with underscores
    .str.replace(r"[^a-zA-Z0-9áéíóú'ÁÉÍÓÚÑ_]", "", regex=True)
)  # Remove non-alphanumeric characters
df.columns

Index(['posición', 'título', 'artista', 'ao', 'lyrics'], dtype='object')

In [21]:
def clean_lyrics(df):
    # Create a copy to avoid modifying the original DataFrame
    df_clean = df.copy()

    # Function to process each lyrics entry
    def process_lyrics(text):
        # Check if the value is NaN
        if pd.isna(text):
            return text  # Keep NaN values as they are
        else:
            # For non-NaN values, split at "Contributors" and take everything after it
            if "Contributors" in text:
                return text.split("Contributors", 1)[-1]
            else:
                return text  # Return original text if "Contributors" not found

    # Apply the function to the lyrics column
    df_clean["lyrics_clean"] = df_clean["lyrics"].apply(process_lyrics)

    return df_clean


df = clean_lyrics(df)
df.head(3)

,posición,título,artista,ao,lyrics,lyrics_clean
0,1,La balsa,Los Gatos,1967,"6 ContributorsLa Balsa Lyrics[Letra de ""La Bal...","La Balsa Lyrics[Letra de ""La Balsa""]\n\n[Verso..."
1,2,Muchacha (Ojos de papel),Almendra,1970,16 ContributorsTranslationsEnglishMuchacha (Oj...,TranslationsEnglishMuchacha (Ojos de Papel) Ly...
2,3,Rasguña las piedras,Sui Generis,1973,10 ContributorsRasguña las Piedras Lyrics[Letr...,"Rasguña las Piedras Lyrics[Letra de ""Rasguña l..."

In [17]:
# Function to clean filenames
def clean_filename(filename):
    # Convert to lowercase
    filename = filename.lower()
    # Replace spaces with underscores
    filename = re.sub(r"\s+", "_", filename)
    # Remove any invalid filename characters
    filename = re.sub(r"[^\w\-_.]", "", filename)
    return filename


# Iterate through the DataFrame
for index, row in df.iterrows():
    try:
        # Get the lyrics, título, and artista
        lyrics = row["lyrics"]
        titulo = row["título"]
        artista = row["artista"]

        # Create and clean filename
        filename = f"{titulo}_{artista}"
        filename = clean_filename(filename)

        # Save lyrics to file
        filepath = f"../outputs/{filename}.txt"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(lyrics)

        print(f"Saved: {filepath}")

    except Exception as e:
        print(f"Error processing row {index}: {e}")

Saved: ../outputs/la_balsa_los_gatos.txt
Saved: ../outputs/muchacha_ojos_de_papel_almendra.txt
Saved: ../outputs/rasguña_las_piedras_sui_generis.txt
Saved: ../outputs/de_música_ligera_soda_stereo.txt
Error processing row 4: write() argument must be str, not float
Saved: ../outputs/sólo_le_pido_a_dios_león_gieco.txt
Saved: ../outputs/presente_el_momento_en_que_estás_vox_dei.txt
Saved: ../outputs/seminare_serú_girán.txt
Saved: ../outputs/y_dale_alegría_a_mi_corazón_fito_páez.txt
Saved: ../outputs/matador_los_fabulosos_cadillacs.txt
Saved: ../outputs/canción_para_mi_muerte_sui_generis.txt
Saved: ../outputs/la_rubia_tarada_sumo.txt
Saved: ../outputs/el_oso_moris.txt
Saved: ../outputs/mil_horas_los_abuelos_de_la_nada.txt
Saved: ../outputs/tengo_sandro.txt
Saved: ../outputs/demoliendo_hoteles_charly_garcía.txt
Saved: ../outputs/yo_vengo_a_ofrecer_mi_corazón_fito_páez.txt
Saved: ../outputs/nada_que_perder_los_pericos.txt
Saved: ../outputs/qué_ves_divididos.txt
Saved: ../outputs/jugo_de_tomate_manal.txt
Saved: ../outputs/imágenes_paganas_virus.txt
Saved: ../outputs/los_viejos_vinagres_sumo.txt
Saved: ../outputs/flaca_andrés_calamaro.txt
Saved: ../outputs/los_dinosaurios_charly_garcía.txt
Saved: ../outputs/el_revelde_la_renga.txt
Saved: ../outputs/verano_del_92_los_piojos.txt
Saved: ../outputs/se_viene_bersuit_vergarabat.txt
Saved: ../outputs/tirá_para_arriba_miguel_mateoszas.txt
Saved: ../outputs/11_y_6_fito_páez.txt
Saved: ../outputs/los_piratas_los_auténticos_decadentes.txt
Saved: ../outputs/persiana_americana_soda_stereo.txt
Saved: ../outputs/la_bestia_pop_patricio_rey_y_sus_redonditos_de_ricota.txt
Saved: ../outputs/seguir_viviendo_sin_tu_amor_luis_alberto_spinetta.txt
Error processing row 33: write() argument must be str, not float
Saved: ../outputs/abarajame_illya_kuryaki_and_the_valderramas.txt
Error processing row 35: write() argument must be str, not float
Saved: ../outputs/y_lo_que_quiero_es_que_pises_sin_el_suelo_catupecu_machu.txt
Saved: ../outputs/sólo_se_trata_de_vivir_litto_nebbia.txt
Saved: ../outputs/spaghetti_del_rock_divididos.txt
Saved: ../outputs/mirta_de_regreso_juan_carlos_baglietto.txt
Error processing row 40: write() argument must be str, not float
Saved: ../outputs/sin_documentos_los_rodríguez.txt
Saved: ../outputs/yo_no_quiero_volverme_tan_loco_charly_garcía.txt
Saved: ../outputs/la_música_el_otro_yo.txt
Saved: ../outputs/hacelo_por_mí_attaque_77.txt
Saved: ../outputs/el_amor_después_del_amor_fito_páez.txt
Error processing row 46: write() argument must be str, not float
Saved: ../outputs/en_la_ciudad_de_la_furia_soda_stereo.txt
Error processing row 48: write() argument must be str, not float
Saved: ../outputs/himno_de_mi_corazón_los_abuelos_de_la_nada.txt
Saved: ../outputs/vasos_vacíos_los_fabulosos_cadillacs.txt
Saved: ../outputs/el_anillo_del_capitán_beto_invisible.txt
Saved: ../outputs/no_llores_por_mí_argentina_serú_girán.txt
Saved: ../outputs/un_poco_de_amor_francés_patricio_rey_y_sus_redonditos_de_ricota.txt
Saved: ../outputs/loco_andrés_calamaro.txt
Saved: ../outputs/pensé_que_se_trataba_de_cieguitos_los_twist.txt
Saved: ../outputs/me_gusta_ese_tajo_pescado_rabioso.txt
Saved: ../outputs/vos_sabés_los_fabulosos_cadillacs.txt
Saved: ../outputs/puente_gustavo_cerati.txt
Saved: ../outputs/mañana_campestre_arco_iris.txt
Error processing row 60: write() argument must be str, not float
Error processing row 61: write() argument must be str, not float
Saved: ../outputs/pupilas_lejanas_los_pericos.txt
Saved: ../outputs/mañana_en_el_abasto_sumo.txt
Error processing row 64: write() argument must be str, not float
Saved: ../outputs/avanti_morocha_los_caballeros_de_la_quema.txt
Error processing row 66: write() argument must be str, not float
Saved: ../outputs/cuando_pase_el_temblor_soda_stereo.txt
Saved: ../outputs/la_muralla_verde_los_enanitos_verdes.txt
Saved: ../outputs/silencio_marginal_aquelarre.txt
Saved: ../outputs/génesis_vox_dei.txt
Saved: ../outputs/trátame_suavemente_los_encargados.txt
Saved: ../outputs/es_la_vida_que_me_alcanza_celeste_carballo.txt
Saved: ../outputs/mujer_amante_rata_blanca.txt
Saved: ../outputs/malón_babasónicos.txt
Saved: ../outputs/loco_tu_forma_de_ser_los_auténticos_decadentes.txt
Saved: ../outputs/el_nuevo_camino_del_hombre_a.n.i.m.a.l..txt
Saved: ../outputs/la_calle_es_su_lugar_g.i.t..txt
Saved: ../outputs/maribel_se_durmió_spinetta_jade.txt
Saved: ../outputs/la_bifurcada_memphis_la_blusera.txt
Saved: ../outputs/chipi_chipi_charly_garcía.txt
Saved: ../outputs/el_bar_de_la_calle_rodney_la_portuaria.txt
Saved: ../outputs/puerto_pollensa_sandra_mihanovich.txt
Saved: ../outputs/hola_qué_tal_las_pelotas.txt
Saved: ../outputs/todo_a_pulmón_alejandro_lerner.txt
Saved: ../outputs/kanishka_los_brujos.txt
Saved: ../outputs/tan_solo_los_piojos.txt
Saved: ../outputs/escafandra_peligrosos_gorriones.txt
Saved: ../outputs/ya_no_sos_igual_dos_minutos.txt
Saved: ../outputs/todo_cambia_man_ray.txt
Saved: ../outputs/playas_oscuras_los_visitantes.txt
Error processing row 91: write() argument must be str, not float
Saved: ../outputs/ella_vendrá_don_cornelio_y_la_zona.txt
Saved: ../outputs/masticar_fun_people.txt
Saved: ../outputs/amanece_en_la_ruta_suéter.txt
Saved: ../outputs/héroes_anónimos_metrópoli.txt
Saved: ../outputs/gente_que_no_todos_tus_muertos.txt
Saved: ../outputs/lollipop_viuda_e_hijas_de_roque_enroll.txt
Saved: ../outputs/me_gustas_mucho_viejas_locas.txt
Saved: ../outputs/morrissey_leo_garcía.txt